FROM openjdk:17-jdk-slim

EXPOSE 8080
ENV TZ=Asia/Seoul

ARG MYSQL_HOST
ARG MYSQL_PORT
ARG MYSQL_USERNAME
ARG MYSQL_PASSWORD
ARG MYSQL_DB_NAME
ARG REDIS_HOST
ARG REDIS_PORT
ARG REDIS_PASSWORD
ARG MONGO_HOST
ARG MONGO_PORT
ARG MONGO_USERNAME
ARG MONGO_PASSWORD
ARG MONGO_DB_NAME
ARG TOKEN_PREFIX
ARG ACCESS_TOKEN_EXP
ARG REFRESH_TOKEN_EXP
ARG TOKEN_SECRET
ARG TOKEN_HEADER
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG GOOGLE_REDIRECT_URI

ENV MYSQL_HOST ${MYSQL_HOST}
ENV MYSQL_PORT ${MYSQL_PORT}
ENV MYSQL_USERNAME ${MYSQL_USERNAME}
ENV MYSQL_PASSWORD ${MYSQL_PASSWORD}
ENV MYSQL_DB_NAME ${MYSQL_DB_NAME}
ENV REDIS_HOST ${REDIS_HOST}
ENV REDIS_PORT ${REDIS_PORT}
ENV REDIS_PASSWORD ${REDIS_PASSWORD}
ENV MONGO_HOST ${MONGO_HOST}
ENV MONGO_PORT ${MONGO_PORT}
ENV MONGO_USERNAME ${MONGO_USERNAME}
ENV MONGO_PASSWORD ${MONGO_PASSWORD}
ENV MONGO_DB_NAME ${MONGO_DB_NAME}
ENV TOKEN_PREFIX ${TOKEN_PREFIX}
ENV ACCESS_TOKEN_EXP ${ACCESS_TOKEN_EXP}
ENV REFRESH_TOKEN_EXP ${REFRESH_TOKEN_EXP}
ENV TOKEN_SECRET ${TOKEN_SECRET}
ENV TOKEN_HEADER ${TOKEN_HEADER}
ENV GOOGLE_CLIENT_ID ${GOOGLE_CLIENT_ID}
ENV GOOGLE_CLIENT_SECRET ${GOOGLE_CLIENT_SECRET}
ENV GOOGLE_REDIRECT_URI ${GOOGLE_REDIRECT_URI}

COPY ./build/libs/*.jar server.jar
ENTRYPOINT ["java","-jar","/server.jar"]
