server:
  port: 8080
  shutdown: graceful


spring:
  r2dbc:
    host: ${MYSQL_HOST:localhost}
    port: ${MYSQL_PORT:3306}
    user: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    database: ${MYSQL_DB_NAME}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      username: ${MONGO_USERNAME:root}
      password: ${MONGO_PASSWORD:1234}
      authentication-database: admin
      database: ${MONGO_DB_NAME:chitchat}

jwt:
  prefix: ${TOKEN_PREFIX:Bearer }
  access-exp: ${ACCESS_TOKEN_EXP:3600}
  refresh-exp: ${REFRESH_TOKEN_EXP:3600}
  secret: ${TOKEN_SECRET}
  header: ${TOKEN_HEADER:Authorization}

oauth:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_REDIRECT_URI}