server:
  port: 8080
  shutdown: graceful


spring:
  r2dbc:
    host: ${DB_HOST:localhost}
    port: ${DB_PORT:5432}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    database: ${DB_NAME}

jwt:
  header: Authorization
  prefix: Bearer
  access-exp: 3600
  refresh-exp: 3600
  secret: testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttest