server:
  port: 8080
  shutdown: graceful


spring:
  r2dbc:
    host: ${DB_HOST:localhost}
    port: ${DB_PORT:5432}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    database: ${DB_NAME}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
    mongodb:
      host: ${DB_HOST:localhost}
      port: ${DB_PORT:27017}
      username: ${MONGODB_USERNAME:root}
      password: ${DB_PASSWORD:1234}
      authentication-database: admin
      database: ${MONGODB_DB_NAME:chitchat}

jwt:
  prefix: ${TOKEN_PREFIX:Bearer }
  access-exp: ${ACCESS_TOKEN_EXP}
  refresh-exp: ${REFRESH_TOKEN_EXP}
  secret: ${TOKEN_SECRET}

oauth:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_REDIRECT_URI}