server:
  port: 8080
  shutdown: graceful


spring:
  r2dbc:
    host: ${DB_HOST:localhost}
    port: ${DB_PORT:5432}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    database: ${DB_NAME}

jwt:
  header: Authorization
  prefix: Bearer
  access-exp: ${ACCESS_TOKEN_EXP}
  refresh-exp: ${REFRESH_TOKEN_EXP}
  secret: ${TOKEN_SECRET}